<?xml version="1.0"?>
<package format="3">
  <name>stl_to_grid_map</name>
  <version>1.0.0</version>
  <description>Convert an STL arena model into an inflated ROS2 occupancy map.</description>
  <maintainer email="student@example.com">student</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>ament_index_python</depend>
  <depend>rclcpp</depend>
  <depend>nav_msgs</depend>
  <exec_depend>ros2launch</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
